# rustfmt configuration file
#
# The following two settings are unstable.
# - imports_granularity
# - imports_layout
#

edition = "2024"
fn_params_layout = "Vertical"
hard_tabs = false
imports_granularity = "Module"
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 110
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
style_edition = "2024"
tab_spaces = 4
