# Run from the repository root with the reference R environment activated.
# Rscript src-cpp/validation/r/generate_descriptive.R
# This script regenerates fixtures deliberately; review numerical changes.

# R's sprintf is not round-trip exact at 17 significant digits: one of the eight
# stored kurtosis values reads back as a neighbouring double. Widen until the
# text denotes the value it was written from, so a fixture says exactly what R
# computed rather than something an ulp away.
number <- function(x) {
  vapply(x, function(value) {
    if (is.na(value)) {
      return(NA_character_)
    }
    for (digits in 17:21) {
      text <- sprintf(paste0("%.", digits, "g"), value)
      if (identical(as.numeric(text), value)) {
        return(text)
      }
    }
    stop("Cannot write ", value, " as text that reads back as the same double.")
  }, character(1))
}

# The format tests/support/fixture.cpp reads. Every key is named, so adding a
# statistic does not shift the meaning of what is already stored, and the loader
# rejects a key it does not know rather than reading past it.
fixture_lines <- function(name, source_label, x, expected) {
  c(
    "# Descriptive reference fixture. Generated by validation/r/generate_descriptive.R.",
    "# R reference values, not measured output from the SPSS application.",
    paste("name =", name),
    paste("source =", source_label),
    paste("total_count =", length(x)),
    paste("valid_count =", sum(!is.na(x))),
    paste("missing_count =", sum(is.na(x))),
    paste(names(expected), "=", number(expected)),
    "[values]",
    ifelse(is.na(x), "NA", number(x))
  )
}

readme_lines <- function(case_count) {
  c(
    "# Descriptive reference fixtures",
    "",
    paste("Generated with", R.version.string),
    paste("datasets:", packageVersion("datasets"), "psych:", packageVersion("psych")),
    "",
    "Source: the iris and airquality objects in R's datasets package; see help(iris) and help(airquality).",
    "Generator: src-cpp/validation/r/generate_descriptive.R (run from repository root).",
    "No rows are reordered or dropped from the saved inputs. NA is a missing row.",
    "Reference calculations omit NA separately for each column. No case weights are used.",
    "Mean, SD, minimum, median and maximum use base R/stats; skew and kurtosis use psych type=2.",
    paste("All", case_count, "reference columns satisfy the SPSS sample-size and variance cutoffs,"),
    "so none of them exercises a statistic that is not returned. Every expected key is required.",
    "",
    "File format:",
    "- Lines starting with # and blank lines are ignored.",
    "- \"key = value\" until the [values] marker. Keys are the field names of the result.",
    "- After [values], one input value per line, or NA for a missing row.",
    "",
    "Both optional statistics are enabled. Counts must match exactly.",
    "Values carry as many significant digits as it takes to read back as the same double.",
    "airquality_solar kurtosis predates that rule and sits one ulp (1.2e-16 relative) from the",
    "value R computed; regenerating widens it by a digit.",
    "Numeric tolerance: the default in src-cpp/docs/NUMERICAL_POLICY.md, which is",
    "absolute 1e-12 plus relative 1e-10 times the expected magnitude. This method does not",
    "override it. The comparison is tests/support/tolerance.hpp.",
    "These are R reference values, not measured outputs from the SPSS application."
  )
}

if (!requireNamespace("psych", quietly = TRUE)) {
  stop("The reference environment requires psych; no packages are installed automatically.")
}

out <- "src-cpp/tests/fixtures/descriptive"
dir.create(out, recursive = TRUE, showWarnings = FALSE)
cases <- list(
  iris_sepal_length = "datasets::iris$Sepal.Length",
  iris_sepal_width = "datasets::iris$Sepal.Width",
  iris_petal_length = "datasets::iris$Petal.Length",
  iris_petal_width = "datasets::iris$Petal.Width",
  airquality_ozone = "datasets::airquality$Ozone",
  airquality_solar = "datasets::airquality$Solar.R",
  airquality_wind = "datasets::airquality$Wind",
  airquality_temp = "datasets::airquality$Temp"
)
for (name in names(cases)) {
  source_label <- cases[[name]]
  x <- eval(parse(text = source_label))
  valid <- x[!is.na(x)]
  stopifnot(length(valid) >= 4, stats::var(valid) >= 1e-20)
  expected <- c(
    mean = mean(valid),
    standard_deviation = stats::sd(valid),
    minimum = min(valid),
    median = stats::median(valid),
    maximum = max(valid),
    skewness = psych::skew(valid, type = 2),
    kurtosis = psych::kurtosi(valid, type = 2)
  )
  stopifnot(all(is.finite(expected)))
  writeLines(fixture_lines(name, source_label, x, expected), file.path(out, paste0(name, ".txt")))
}
writeLines(readme_lines(length(cases)), file.path(out, "README.md"))
cat("Generated", length(cases), "descriptive reference fixtures in", out, "\n")
